var GAME_LEVELS = [

  ["xx                          xxxxxxxxxxxxxxx     xxxxx         ",
   "x=                          xxxxx     xxxxxxxxxxxxxxx         ",
   "x=                          xxxxxxxxxxxxxxx     xxxxx         ",
   "x=                          xxxxx     xxxxxxxxxxxxxxxxx       ",
   "x=                          xxxxxxxxxxxxxxx     xxxxxxxx      ",
   "x=                          xvvvv     vvvvv     vvvvvxxxx  e  ",
   "x=                          x                              xxx",
   "x=                          x                              xxx",
   "x=                          x     xxx       xxx           xxxx",
   "x=                      xx                               xxxxx",
   "x=        @            xxx                              xxxxxx",
   "xxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",],


   ["vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvx",
    "x                                 x",
    "x                                 x",
    "x                                 x",
    "x @                               x",
    "xxxx                              x",
    "x                                 x",
    "x                                 x",
    "x   xxx                           x",
    "x                                 x",
    "x                                 x",
    "xxxx                              x",
    "x                                 x",
    "x   xxxx  xxx  xxx                x",
    "x                                 x",
    "x                  xxx xxx        x",
    "x                  vvv vvv        x",
    "x                           xxx   x",
    "x                                 x",
    "x                         xx      x",
    "x    !!!!!!!!!!                   x",
    "x    xxxxxxxxxx                   x",
    "x                 xxxxxxxx        x",
    "x  e                              x",
    "xxxxxxxxxxxxxxxxx                 x",
    "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",],


    ["                                     x       ",
     "x=                                   x       ",
     "x=                                   x       ",
     "x=                            x      x       ",
     "x=                           x!      x       ",
     "x=                      x   xxx!     x       ",
     "x=                          xxxx   !!x       ",
     "x=                        xxxxxx   xxx       ",
     "x=                      xxxxxxxx     x       ",
     "x=                        xxxxxx     x       ",
     "x=                   x    xxxxxx    !x       ",
     "x=                       xxxxxxx    xx       ",
     "x=                     xxxxxxxxx!    x       ",
     "x=                  xxxxxxxxxxxxx!   x       ",
     "x=        @       xxxxxxxxxxxxxxxx!          ",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       e  ",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",],


  ["                                                                 ",
   "                                                                 ",
   "     @                                                           ",
   "    xxx                                                          ",
   "                                                                 ",
   "                                                                 ",
   "!!!!!!!!!                                                        ",
   "xxxxxxxxx                                                        ",
   "                                                                 ",
   "                                                                 ",
   "                                                                 ",
   "          xxx   !                                                ",
   "        !!!!!!!!x                                                ",
   "        xxxxxxxxx                                                ",
   "           |                                                     ",
   "                   xxxxx                                         ",
   "                  x        !                                     ",
   "   xxx  xx  xx  xx         xx                                    ",
   "              |                                                  ",
   "                                !      !!                        ",
   "           x  x                 xxx   xxx                        ",
   "                                                                 ",
   "                                                                 ",
   "                                                             xx  ",
   "                                    !!      !                 x  ",
   "                                    xxxx  xxxx                x  ",
   "                                                              x  ",
   "                                                 xxx     e    x  ",
   "                                                       xxxxxxxx  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx  "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
